import{menmacmd as c}from"../lib/menmacmd.js";import u from"axios";import"../config.js";import e from"../lib/styleHelper.js";import{trd as a}from"../lib/i18n.js";const m=e.GENERATED_BY,d={af:"Afrikaans",sq:"Albanais",am:"Amharique",ar:"Arabe",hy:"Arm\xE9nien",az:"Azerba\xEFdjanais",eu:"Basque",be:"Bi\xE9lorusse",bn:"Bengali",bs:"Bosniaque",bg:"Bulgare",ca:"Catalan","zh-cn":"Chinois simplifi\xE9","zh-tw":"Chinois traditionnel",hr:"Croate",cs:"Tch\xE8que",da:"Danois",nl:"N\xE9erlandais",en:"Anglais",eo:"Esp\xE9ranto",et:"Estonien",fi:"Finnois",fr:"Fran\xE7ais",gl:"Galicien",ka:"G\xE9orgien",de:"Allemand",el:"Grec",gu:"Gujarati",ht:"Ha\xEFtien",iw:"H\xE9breu",hi:"Hindi",hu:"Hongrois",id:"Indon\xE9sien",ga:"Irlandais",it:"Italien",ja:"Japonais",kn:"Kannada",kk:"Kazakh",km:"Khmer",ko:"Cor\xE9en",lo:"Laotien",lv:"Letton",lt:"Lituanien",mk:"Mac\xE9donien",ms:"Malais",ml:"Malayalam",mt:"Maltais",mr:"Marathi",mn:"Mongol",my:"Birman",ne:"N\xE9palais",no:"Norv\xE9gien",fa:"Persan",pl:"Polonais",pt:"Portugais",ro:"Roumain",ru:"Russe",sr:"Serbe",si:"Cingalais",sk:"Slovaque",sl:"Slov\xE8ne",es:"Espagnol",sw:"Swahili",sv:"Su\xE9dois",tl:"Tagalog",ta:"Tamoul",te:"T\xE9lougou",th:"Tha\xEF",tr:"Turc",uk:"Ukrainien",ur:"Ourdou",vi:"Vietnamien",cy:"Gallois",yo:"Yoruba",zu:"Zoulou"};c({name:a("translate.name"),alias:["trl","trad","tr"],classe:"outils",react:"\u{1F30D}",desc:a("translate.desc")},async(h,g,{repondre:t,arg:s,msg_Repondu:r,prefixe:i})=>{if(!s[0]||["list","liste"].includes(s[0])){let o=e.TOP(a("translate.title"))+`
`;return Object.entries(d).forEach(([p,y])=>{o+=e.LINE(`${p} \u2014 ${y}
`)}),t(o+e.INTER()+`
`+e.LINE(a("translate.usage",{prefixe:i})+`
`)+e.BTM+m)}let n=s[0],l=s.slice(1).join(" ")||(r?r.conversation||r.extendedTextMessage?.text:"");if(!d[n])return t(a("translate.unknown",{lang:n,prefixe:i}));if(!l)return t(a("translate.error_usage",{prefixe:i}));try{const o=await u.get(`https://api.popcat.xyz/translate?to=${n}&text=${encodeURIComponent(l)}`);t(a("translate.result",{lang:d[n],text:o.data.translated})+m)}catch{t(a("misc.error"))}}),c({name:a("weather.name"),alias:["meteo"],classe:"outils",react:"\u2601\uFE0F",desc:a("weather.desc")},async(h,g,{repondre:t,arg:s,prefixe:r})=>{if(!s[0])return t(a("weather.usage",{prefixe:r}));try{const n=(await u.get(`https://api.popcat.xyz/weather?q=${encodeURIComponent(s.join(" "))}`)).data[0];if(!n)return t(a("weather.not_found"));t(e.TOP(a("weather.title"))+`
`+e.LINE(a("weather.result",{city:n.location.name,temp:n.current.temperature,sky:n.current.skytext,humidity:n.current.humidity,wind:n.current.winddisplay})+`
`)+e.BTM+m)}catch{t(a("weather.error"))}}),c({name:a("repo.name"),classe:"outils",react:"\u{1F9EC}",desc:a("repo.desc")},async(h,g,{repondre:t})=>{try{const{data:s}=await u.get("https://api.github.com/repos/Dr-Djibi/Menma-MD");let r=e.TOP("MENMA-MD")+`
`+e.LINE(a("repo.stars",{count:s.stargazers_count})+`
`)+e.LINE(a("repo.forks",{count:s.forks_count})+`
`)+a("repo.url",{url:s.html_url})+`
`+e.BTM+m;t(r)}catch{t(a("repo.fallback"))}}),c({name:a("tempmail.name"),alias:["mail","genmail"],classe:"outils",react:"\u{1F4E7}",desc:a("tempmail.desc")},async(h,g,{repondre:t})=>{try{const{data:s}=await u.get("https://api.siputzx.my.id/api/tools/tempmail/create");if(!s.status||!s.result)return t(a("tempmail.error"));t(a("tempmail.result",{email:s.result})+m)}catch{t(a("tempmail.error"))}}),c({name:a("checkmail.name"),alias:["readmail"],classe:"outils",react:"\u{1F4E5}",desc:a("checkmail.desc")},async(h,g,{repondre:t,arg:s,prefixe:r})=>{if(!s[0])return t(a("checkmail.usage",{prefixe:r}));try{const{data:i}=await u.get(`https://api.siputzx.my.id/api/tools/tempmail/getMessages?email=${encodeURIComponent(s[0])}`);if(!i.status||!i.result||i.result.length===0)return t(a("checkmail.empty"));let n=e.TOP(a("checkmail.title"))+`
`;i.result.forEach((l,o)=>{n+=e.LINE(`\u{1F4E9} *Mail #${o+1}*
`)+e.LINE(`\u{1F464} *De :* ${l.from}
`)+e.LINE(`\u{1F4DD} *Sujet :* ${l.subject}
`)+e.LINE(`\u{1F4C5} *Re\xE7u :* ${l.date}
`)+e.LINE(`\u{1F4C4} *Contenu :* 
${l.body}
`)+e.INTER()+`
`}),t(n+e.BTM+m)}catch{t(a("checkmail.error"))}});
