import{menmacmd as g}from"../lib/menmacmd.js";import b from"axios";import s from"../lib/styleHelper.js";import{trd as a}from"../lib/i18n.js";const w=s.GENERATED_BY,f=[{name:"hentai",url:"hentai",react:"\u{1F51E}",api:"waifu"},{name:"nsfwneko",url:"neko",react:"\u{1F431}",api:"waifu"},{name:"trap",url:"trap",react:"\u{1F457}",api:"waifu"},{name:"blowjob",url:"blowjob",react:"\u{1F444}",api:"waifu"},{name:"waifu_nsfw",url:"waifu",react:"\u{1F457}",api:"waifu"},{name:"ero",url:"ero",react:"\u{1F351}",api:"waifu"},{name:"milf",url:"milf",react:"\u{1F469}",api:"waifu"},{name:"oral",url:"oral",react:"\u{1F445}",api:"waifu"},{name:"paizuri",url:"paizuri",react:"\u{1F352}",api:"waifu"},{name:"ecchi",url:"ecchi",react:"\u{1F9F4}",api:"waifu"},{name:"neko_best",url:"neko",react:"\u{1F408}",api:"nekos"},{name:"waifu_best",url:"waifu",react:"\u2728",api:"nekos"},{name:"trap_best",url:"trap",react:"\u{1F460}",api:"nekos"},{name:"blowjob_best",url:"blowjob",react:"\u{1F4A6}",api:"nekos"}];async function d(e){try{const{data:r}=await b.get(`https://nekos.best/api/v2/${e.url}`,{timeout:8e3});if(r?.results?.[0]?.url)return r.results[0].url}catch(r){console.error(`[NSFW] \xC9chec nekos.best pour ${e.url}: ${r.message}`)}return null}g({name:a("nsfw.name"),alias:["18+","xxx","sex"],react:"\u{1F51E}",classe:"NSFW",desc:a("nsfw.desc")},async(e,r,{repondre:u,arg:c,prefixe:i,ms:t})=>{try{if(!c[0]){let n=s.TOP(a("nsfw.title")||"\u{1F51E} MENU NSFW")+`
`;return n+=s.LINE(`${a("nsfw.warning")||"Attention : Ce menu contient du contenu pour adultes."}
`),n+=s.INTER()+`
`,f.forEach((l,E)=>{n+=s.LINE(`  *${E+1}.* ${l.name.toUpperCase()}
`)}),n+=s.INTER()+`
`,n+=s.LINE(`${a("nsfw.usage",{prefixe:i})||"Utilisation : "+i+"nsfw <num\xE9ro/nom>"}
`),n+=s.BTM+w,await r.sendMessage(e,{text:n},{quoted:t})}const o=c[0].toLowerCase(),m=f.find((n,l)=>n.name===o||o===(l+1).toString());if(!m)return u(a("nsfw.unknown",{choice:o,prefixe:i})||`Cat\xE9gorie "${o}" inconnue.`);const p=await d(m);if(!p)throw new Error(a("nsfw.no_media")||"Impossible de r\xE9cup\xE9rer l'image.");await r.sendMessage(e,{image:{url:p},caption:(a("nsfw.caption",{category:m.name.toUpperCase()})||`\u{1F51E} *${m.name.toUpperCase()}*`)+`
`+w},{quoted:t})}catch(o){u(a("nsfw.error",{error:o.message})||`\u274C Erreur : ${o.message}`)}}),f.forEach(e=>{g({name:e.name,alias:[e.url+"_nsfw"],react:e.react,classe:"NSFW",desc:`Commande ${e.name}`},async(r,u,{repondre:c,ms:i})=>{try{const t=await d(e);if(!t)throw new Error(a("nsfw.no_media")||"Impossible de r\xE9cup\xE9rer l'image.");await u.sendMessage(r,{image:{url:t},caption:`\u{1F51E} *${e.name.toUpperCase()}*
`+w},{quoted:i})}catch(t){c(a("nsfw.error",{error:t.message})||`\u274C Erreur : ${t.message}`)}})});
