import{menmacmd as E}from"../lib/menmacmd.js";import s from"../lib/styleHelper.js";import"../lib/utils/cache.js";import{trd as e}from"../lib/i18n.js";import"@whiskeysockets/baileys";const v=s.GENERATED_BY;E({name:e("kick.name"),alias:["virer","retirer"],classe:"groupe",react:"\u{1F9B6}",desc:e("kick.desc")},async(r,n,{repondre:t,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o,mr:c,auteur_Msg_Repondu:u,ms:m})=>{if(!i)return t(e("misc.group"));if(!o)return t(e("misc.admin"));if(!a)return t(e("misc.botAdmin"));const l=c&&c[0]||u;if(!l)return t(s.TOP("\u274C ERREUR")+`
`+s.LINE(`${e("kick.usage")}
`)+s.BTM);try{await n.groupParticipantsUpdate(r,[l],"remove"),t({text:e("kick.success",{user:l.split("@")[0]}),mentions:[l]})}catch{t(e("misc.error"))}}),E({name:e("add.name"),alias:["ajouter"],classe:"groupe",react:"\u2795",desc:e("add.desc")},async(r,n,{repondre:t,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o,arg:c,prefixe:u})=>{if(!i)return t(e("misc.group"));if(!o)return t(e("misc.admin"));if(!a)return t(e("misc.botAdmin"));let m=c[0];if(!m)return t(s.TOP("\u274C ERREUR")+`
`+s.LINE(`${e("add.usage",{prefixe:u})}
`)+s.BTM);m=m.replace(/\D/g,"");const l=`${m}@s.whatsapp.net`;try{await n.groupParticipantsUpdate(r,[l],"add"),t({text:e("add.success",{user:m}),mentions:[l]})}catch{t(e("misc.error"))}}),E({name:e("promote.name"),alias:["admin","promouvoir"],classe:"groupe",react:"\u{1F53A}",desc:e("promote.desc")},async(r,n,{repondre:t,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o,mr:c,auteur_Msg_Repondu:u})=>{if(!i)return t(e("misc.group"));if(!o)return t(e("misc.admin"));if(!a)return t(e("misc.botAdmin"));const m=c&&c[0]||u;if(!m)return t(s.TOP("\u274C ERREUR")+`
`+s.LINE(`${e("promote.usage")}
`)+s.BTM);try{await n.groupParticipantsUpdate(r,[m],"promote"),t({text:e("promote.success",{user:m.split("@")[0]}),mentions:[m]})}catch{t(e("misc.error"))}}),E({name:e("demote.name"),alias:["deadmin","retrograder"],classe:"groupe",react:"\u{1F53B}",desc:e("demote.desc")},async(r,n,{repondre:t,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o,mr:c,auteur_Msg_Repondu:u})=>{if(!i)return t(e("misc.group"));if(!o)return t(e("misc.admin"));if(!a)return t(e("misc.botAdmin"));const m=c&&c[0]||u;if(!m)return t(s.TOP("\u274C ERREUR")+`
`+s.LINE(`${e("demote.usage")}
`)+s.BTM);try{await n.groupParticipantsUpdate(r,[m],"demote"),t({text:e("demote.success",{user:m.split("@")[0]}),mentions:[m]})}catch{t(e("misc.error"))}}),E({name:e("tagall.name"),alias:["tous","all"],classe:"groupe",react:"\u{1F4E3}",desc:e("tagall.desc")},async(r,n,t)=>{const{repondre:i,verif_Gp:a,verif_Admin:o,mbre_membre:c,arg:u,resolveName:m,auteur_Message:l,ms:N,msg_Repondu:g}=t;if(!a)return i(e("misc.group"));if(!o)return i(e("misc.admin"));const R=m(l),f=c.map(M=>M.id);let p=`

\u{1F4E2} *Appel par :* ${R}
`+s.INTER()+`
`;for(let M of c)p+=s.LINE(`\u{1F538} @${M.id.split("@")[0]}
`);if(p+=s.LINE(`${e("tagall.total",{count:c.length})}
`)+s.BTM,g){const M=Object.keys(g)[0],y=g[M],w=u.join(" ");if(M==="imageMessage"||M==="videoMessage"){const d=(w||y.caption||"")+p;return await n.sendMessage(r,{[M.replace("Message","")]:y,caption:d,mentions:f})}if(M==="conversation"||M==="extendedTextMessage"){const d=(w||y.text||y||"")+p;return await n.sendMessage(r,{text:d,mentions:f})}if(M==="stickerMessage")return await i("\u26A0\uFE0F *Note :* Tagall avec liste visible impossible sur un sticker. Passage en mode *invisible*."),await n.sendMessage(r,{sticker:y.url?{url:y.url}:y,mentions:f});if(y.caption!==void 0){const d=(w||y.caption||"")+p;return await n.sendMessage(r,{[M.replace("Message","")]:y,caption:d,mentions:f})}}const b=u.join(" ")||e("tagall.msg");let T=s.TOP(e("tagall.title"))+`
`;T+=s.LINE(`${e("tagall.label_msg")}
`),T+=s.LINE(`${b}
`),T+=p,await n.sendMessage(r,{text:T,mentions:f})}),E({name:e("hidetag.name"),alias:["tag","invisible"],classe:"groupe",react:"\u{1F47B}",desc:e("hidetag.desc")},async(r,n,t)=>{const{repondre:i,verif_Gp:a,verif_Admin:o,mbre_membre:c,arg:u,ms:m,msg_Repondu:l}=t;if(!a)return i(e("misc.group"));if(!o)return i(e("misc.admin"));const N=c.map(f=>f.id),g=u.join(" ");if(l){const f=Object.keys(l)[0],p=l[f];let b={mentions:N};if(f==="conversation"||f==="extendedTextMessage")b.text=g||p.text||p||"\u{1F4E3}";else if(f==="stickerMessage")b.sticker=p;else if(f==="imageMessage")b.image=p,b.caption=g||p.caption||"";else if(f==="videoMessage")b.video=p,b.caption=g||p.caption||"";else if(f==="audioMessage")b.audio=p;else{const T=f.replace("Message","");b[T]=p,p.caption!==void 0&&(b.caption=g||p.caption||"")}return await n.sendMessage(r,b)}const R=g||"\u{1F4E3}";await n.sendMessage(r,{text:R,mentions:N})}),E({name:e("open.name"),alias:["ouvrir","ouvrirgroupe"],classe:"groupe",react:"\u{1F513}",desc:e("open.desc")},async(r,n,{repondre:t,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o})=>{if(!i)return t(e("misc.group"));if(!o)return t(e("misc.admin"));if(!a)return t(e("misc.botAdmin"));try{await n.groupSettingUpdate(r,"not_announcement"),t(e("open.success"))}catch{t(e("misc.error"))}}),E({name:e("close.name"),alias:["fermer","fermergroupe"],classe:"groupe",react:"\u{1F512}",desc:e("close.desc")},async(r,n,{repondre:t,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o})=>{if(!i)return t(e("misc.group"));if(!o)return t(e("misc.admin"));if(!a)return t(e("misc.botAdmin"));try{await n.groupSettingUpdate(r,"announcement"),t(e("close.success"))}catch{t(e("misc.error"))}}),E({name:e("listmembers.name"),alias:["membres","listmembre"],classe:"groupe",react:"\u{1F465}",desc:e("listmembers.desc")},async(r,n,{repondre:t,verif_Gp:i,mbre_membre:a,nom_Gp:o,resolveName:c})=>{if(!i)return t(e("misc.group"));let u="",m="",l=0,N=0;a.forEach(f=>{const p=c(f.id);f.admin?(l++,u+=s.LINE(`${l}. ${p}
`)):(N++,m+=s.LINE(`${N}. ${p}
`))});let g=s.TOP(e("listmembers.title",{group:o.toUpperCase()}))+`
`;g+=s.LINE(`${e("listmembers.total",{count:a.length})}
`),l>0&&(g+=s.INTER()+`
`,g+=s.LINE(`${e("listmembers.admins",{count:l})}
`)+u),N>0&&(g+=s.INTER()+`
`,g+=s.LINE(`${e("listmembers.members",{count:N})}
`)+m),g+=s.BTM;const R=a.map(f=>f.id);await n.sendMessage(r,{text:g+v,mentions:R})}),E({name:e("setdesc.name"),alias:["desc","description"],classe:"groupe",react:"\u{1F4DD}",desc:e("setdesc.desc")},async(r,n,{repondre:t,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o,arg:c,prefixe:u})=>{if(!i)return t(e("misc.group"));if(!o)return t(e("misc.admin"));if(!a)return t(e("misc.botAdmin"));const m=c.join(" ");if(!m)return t(s.TOP("\u274C ERREUR")+`
`+s.LINE(`${e("setdesc.usage",{prefixe:u})}
`)+s.BTM);try{await n.groupUpdateDescription(r,m),t(e("setdesc.success"))}catch{t(e("misc.error"))}}),E({name:e("setname.name"),alias:["renommer","nomgroupe"],classe:"groupe",react:"\u270F\uFE0F",desc:e("setname.desc")},async(r,n,{repondre:t,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o,arg:c,prefixe:u})=>{if(!i)return t(e("misc.group"));if(!o)return t(e("misc.admin"));if(!a)return t(e("misc.botAdmin"));const m=c.join(" ");if(!m)return t(s.TOP("\u274C ERREUR")+`
`+s.LINE(`${e("setname.usage",{prefixe:u})}
`)+s.BTM);try{await n.groupUpdateSubject(r,m),t(e("setname.success",{name:m}))}catch{t(e("misc.error"))}}),E({name:e("linkgroupe.name"),alias:["link","invitelink"],classe:"groupe",react:"\u{1F517}",desc:e("linkgroupe.desc")},async(r,n,{repondre:t,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o})=>{if(!i)return t(e("misc.group"));if(!o)return t(e("misc.admin"));if(!a)return t(e("misc.botAdmin"));try{const c=await n.groupInviteCode(r);t(e("linkgroupe.msg",{code:c}))}catch{t(e("misc.error"))}}),E({name:e("infogroupe.name"),alias:["groupinfo","infogp"],classe:"groupe",react:"\u2139\uFE0F",desc:e("infogroupe.desc")},async(r,n,{repondre:t,verif_Gp:i,infos_Gp:a,mbre_membre:o,admins:c})=>{if(!i)return t(e("misc.group"));const u=a.creation?new Date(a.creation*1e3).toLocaleDateString("fr-FR"):"Inconnue",m=`${s.TOP(e("infogroupe.title"))}
${s.LINE(e("infogroupe.label_name",{name:a.subject||"N/A"}))}
${s.LINE(e("infogroupe.label_members",{count:o.length}))}
${s.LINE(e("infogroupe.label_admins",{count:c.length}))}
${s.LINE(e("infogroupe.label_date",{date:u}))}
${s.BTM}
${s.TOP(e("infogroupe.label_desc"))}
${a.desc||e("infogroupe.no_desc")}`;t(m+v)}),E({name:e("clear.name"),alias:["clean","vider"],classe:"groupe",react:"\u{1F9F9}",desc:e("clear.desc")},async(r,n,{repondre:t,verif_Admin:i,is_Owner:a,verif_Gp:o,ms:c})=>{if(o&&!i&&!a)return t(e("clear.no_admin"));if(!o&&!a)return t(e("misc.owner"));try{const u={key:c.key,messageTimestamp:c.messageTimestamp};try{await n.chatModify({clear:{messages:[u]}},r)}catch{await n.chatModify({clear:!0,lastMessages:[u]},r)}t(s.TOP("NETTOYAGE")+`
`+s.LINE(`${e("clear.success")}
`)+s.BTM)}catch(u){console.error("[CLEAR ERROR]",u),t(s.TOP("\u274C ERREUR")+`
`+s.LINE(`${e("clear.error")}
`)+s.BTM)}});import"../Database/settings.js";E({name:"setfooter",alias:["footer"],classe:"outils",react:"\u{1F58B}\uFE0F",desc:"Configure le footer personnalis\xE9 du bot (appara\xEEt sur les commandes)."},async(r,n,{repondre:t,is_Owner:i,arg:a})=>{if(!i)return t("\u274C Cette commande est r\xE9serv\xE9e au propri\xE9taire.");const o=a.join(" ");if(!o)return t(`\u274C Veuillez entrer le texte de votre footer apr\xE8s la commande.

*Exemple* : .setfooter Cr\xE9\xE9 par Dr Djibi`);try{const{updateSetting:c}=await import("../Database/settings.js");await c("customFooter",o),t(`\u2705 *Footer personnalis\xE9 enregistr\xE9 !*

Il s'affichera d\xE9sormais sur le menu et les autres commandes officielles.`)}catch{t(e("misc.error"))}}),E({name:"getfooter",alias:["viewfoot","showfooter"],classe:"outils",react:"\u{1F440}",desc:"Voir le footer personnalis\xE9 actuel."},async(r,n,{repondre:t,is_Owner:i})=>{if(!i)return t(e("misc.owner"));try{const{getSettings:a}=await import("../Database/settings.js"),o=await a();if(!o.customFooter)return t("\u2139\uFE0F Aucun footer personnalis\xE9 n'est configur\xE9.");t(`\u{1F4DD} *Votre footer actuel :*

${o.customFooter}`)}catch{t(e("misc.error"))}}),E({name:"delfooter",alias:["delfoot","removefooter"],classe:"outils",react:"\u{1F9F9}",desc:"Supprimer le footer personnalis\xE9."},async(r,n,{repondre:t,is_Owner:i})=>{if(!i)return t(e("misc.owner"));try{const{updateSetting:a}=await import("../Database/settings.js");await a("customFooter",""),t("\u2705 *Footer personnalis\xE9 supprim\xE9 avec succ\xE8s !*")}catch{t(e("misc.error"))}});import k from"../config.js";import{getAllSudoNumbers as L}from"../Database/sudo.js";E({name:e("kickcountry.name")||"kickcountry",alias:["kickprefix","virepays","kicknum"],classe:"groupe",react:"\u{1F30D}",desc:e("kickcountry.desc")||"Expulser tous les membres non-admin ayant un indicatif pays sp\xE9cifique (ex: .kickcountry 234)."},async(r,n,t)=>{const{repondre:i,verif_Gp:a,verif_Admin:o,verif_menmaAdmin:c,arg:u,mbre_membre:m,prefixe:l}=t;if(!a)return i(e("misc.group"));if(!o)return i(e("misc.admin"));if(!c)return i(e("misc.botAdmin"));if(!u[0])return i(s.TOP("\u{1F30D} KICK COUNTRY")+`
`+s.LINE(`${e("kickcountry.usage",{prefixe:l})||"*Usage* : "+l+`kickcountry <indicatif>
*Exemple* : `+l+"kickcountry 234,212"}
`)+s.BTM);const g=u.join(" ").split(/[,;\s]+/).map(R=>R.replace(/\D/g,"")).filter(Boolean);if(g.length===0)return i(s.TOP("\u274C ERREUR")+`
`+s.LINE(`Veuillez fournir au moins un indicatif num\xE9rique valide.
Ex: ${l}kickcountry 234
`)+s.BTM);try{const R=(n.user?.id||"").split(":")[0]+"@s.whatsapp.net",f=(Array.isArray(k.NUMERO_DEV)?k.NUMERO_DEV:[k.NUMERO_DEV]).map(d=>String(d).replace(/\D/g,"")),p=(Array.isArray(k.NUMERO_DEV_LID)?k.NUMERO_DEV_LID:[k.NUMERO_DEV_LID]).map(d=>String(d).replace(/\D/g,"")),b=String(k.OWNER||"").replace(/\D/g,""),T=(await L().catch(()=>[])).map(d=>String(d).replace(/\D/g,"")),M=new Set([...f,...p,b,...T].filter(Boolean)),y=[];for(const d of m){if(d.admin||d.superadmin)continue;const I=d.id||"";if(I===R)continue;const h=I.split("@")[0].split(":")[0];if(M.has(h))continue;g.some($=>h.startsWith($))&&y.push(I)}if(y.length===0)return i(s.TOP("\u{1F30D} KICK COUNTRY")+`
`+s.LINE(`${e("kickcountry.empty",{prefixes:g.map(d=>"+"+d).join(", ")})||"Aucun membre non-admin trouv\xE9 avec l'indicatif "+g.map(d=>"+"+d).join(", ")+"."}
`)+s.BTM);await n.groupParticipantsUpdate(r,y,"remove");const w=s.TOP("\u{1F30D} KICK COUNTRY")+`
`+s.LINE(`\u2705 *${y.length}* membres (${g.map(d=>"+"+d).join(", ")}) ont \xE9t\xE9 expuls\xE9s du groupe.
`)+s.BTM;i(w)}catch(R){console.error("[KICKCOUNTRY ERR]",R),i(e("misc.error"))}});
