import{menmacmd as p}from"../lib/menmacmd.js";import t from"../lib/styleHelper.js";import"../lib/utils/cache.js";import{trd as e}from"../lib/i18n.js";import"@whiskeysockets/baileys";const N=t.GENERATED_BY;p({name:e("kick.name"),alias:["virer","retirer"],classe:"groupe",react:"\u{1F9B6}",desc:e("kick.desc")},async(n,c,{repondre:s,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o,mr:r,auteur_Msg_Repondu:u,ms:m})=>{if(!i)return s(e("misc.group"));if(!o)return s(e("misc.admin"));if(!a)return s(e("misc.botAdmin"));const l=r&&r[0]||u;if(!l)return s(t.TOP("\u274C ERREUR")+`
`+t.LINE(`${e("kick.usage")}
`)+t.BTM);try{await c.groupParticipantsUpdate(n,[l],"remove"),s({text:e("kick.success",{user:l.split("@")[0]}),mentions:[l]})}catch{s(e("misc.error"))}}),p({name:e("add.name"),alias:["ajouter"],classe:"groupe",react:"\u2795",desc:e("add.desc")},async(n,c,{repondre:s,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o,arg:r,prefixe:u})=>{if(!i)return s(e("misc.group"));if(!o)return s(e("misc.admin"));if(!a)return s(e("misc.botAdmin"));let m=r[0];if(!m)return s(t.TOP("\u274C ERREUR")+`
`+t.LINE(`${e("add.usage",{prefixe:u})}
`)+t.BTM);m=m.replace(/\D/g,"");const l=`${m}@s.whatsapp.net`;try{await c.groupParticipantsUpdate(n,[l],"add"),s({text:e("add.success",{user:m}),mentions:[l]})}catch{s(e("misc.error"))}}),p({name:e("promote.name"),alias:["admin","promouvoir"],classe:"groupe",react:"\u{1F53A}",desc:e("promote.desc")},async(n,c,{repondre:s,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o,mr:r,auteur_Msg_Repondu:u})=>{if(!i)return s(e("misc.group"));if(!o)return s(e("misc.admin"));if(!a)return s(e("misc.botAdmin"));const m=r&&r[0]||u;if(!m)return s(t.TOP("\u274C ERREUR")+`
`+t.LINE(`${e("promote.usage")}
`)+t.BTM);try{await c.groupParticipantsUpdate(n,[m],"promote"),s({text:e("promote.success",{user:m.split("@")[0]}),mentions:[m]})}catch{s(e("misc.error"))}}),p({name:e("demote.name"),alias:["deadmin","retrograder"],classe:"groupe",react:"\u{1F53B}",desc:e("demote.desc")},async(n,c,{repondre:s,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o,mr:r,auteur_Msg_Repondu:u})=>{if(!i)return s(e("misc.group"));if(!o)return s(e("misc.admin"));if(!a)return s(e("misc.botAdmin"));const m=r&&r[0]||u;if(!m)return s(t.TOP("\u274C ERREUR")+`
`+t.LINE(`${e("demote.usage")}
`)+t.BTM);try{await c.groupParticipantsUpdate(n,[m],"demote"),s({text:e("demote.success",{user:m.split("@")[0]}),mentions:[m]})}catch{s(e("misc.error"))}}),p({name:e("tagall.name"),alias:["tous","all"],classe:"groupe",react:"\u{1F4E3}",desc:e("tagall.desc")},async(n,c,s)=>{const{repondre:i,verif_Gp:a,verif_Admin:o,mbre_membre:r,arg:u,resolveName:m,auteur_Message:l,ms:y,msg_Repondu:d}=s;if(!a)return i(e("misc.group"));if(!o)return i(e("misc.admin"));const w=m(l),g=r.map(b=>b.id);let f=`

\u{1F4E2} *Appel par :* ${w}
`+t.INTER()+`
`;for(let b of r)f+=t.LINE(`\u{1F538} @${b.id.split("@")[0]}
`);if(f+=t.LINE(`${e("tagall.total",{count:r.length})}
`)+t.BTM,d){const b=Object.keys(d)[0],M=d[b],$=u.join(" ");if(b==="imageMessage"||b==="videoMessage"){const R=($||M.caption||"")+f;return await c.sendMessage(n,{[b.replace("Message","")]:M,caption:R,mentions:g})}if(b==="conversation"||b==="extendedTextMessage"){const R=($||M.text||M||"")+f;return await c.sendMessage(n,{text:R,mentions:g})}if(b==="stickerMessage")return await i("\u26A0\uFE0F *Note :* Tagall avec liste visible impossible sur un sticker. Passage en mode *invisible*."),await c.sendMessage(n,{sticker:M.url?{url:M.url}:M,mentions:g});if(M.caption!==void 0){const R=($||M.caption||"")+f;return await c.sendMessage(n,{[b.replace("Message","")]:M,caption:R,mentions:g})}}const E=u.join(" ")||e("tagall.msg");let T=t.TOP(e("tagall.title"))+`
`;T+=t.LINE(`${e("tagall.label_msg")}
`),T+=t.LINE(`${E}
`),T+=f,await c.sendMessage(n,{text:T,mentions:g})}),p({name:e("hidetag.name"),alias:["tag","invisible"],classe:"groupe",react:"\u{1F47B}",desc:e("hidetag.desc")},async(n,c,s)=>{const{repondre:i,verif_Gp:a,verif_Admin:o,mbre_membre:r,arg:u,ms:m,msg_Repondu:l}=s;if(!a)return i(e("misc.group"));if(!o)return i(e("misc.admin"));const y=r.map(g=>g.id),d=u.join(" ");if(l){const g=Object.keys(l)[0],f=l[g];let E={mentions:y};if(g==="conversation"||g==="extendedTextMessage")E.text=d||f.text||f||"\u{1F4E3}";else if(g==="stickerMessage")E.sticker=f;else if(g==="imageMessage")E.image=f,E.caption=d||f.caption||"";else if(g==="videoMessage")E.video=f,E.caption=d||f.caption||"";else if(g==="audioMessage")E.audio=f;else{const T=g.replace("Message","");E[T]=f,f.caption!==void 0&&(E.caption=d||f.caption||"")}return await c.sendMessage(n,E)}const w=d||"\u{1F4E3}";await c.sendMessage(n,{text:w,mentions:y})}),p({name:e("open.name"),alias:["ouvrir","ouvrirgroupe"],classe:"groupe",react:"\u{1F513}",desc:e("open.desc")},async(n,c,{repondre:s,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o})=>{if(!i)return s(e("misc.group"));if(!o)return s(e("misc.admin"));if(!a)return s(e("misc.botAdmin"));try{await c.groupSettingUpdate(n,"not_announcement"),s(e("open.success"))}catch{s(e("misc.error"))}}),p({name:e("close.name"),alias:["fermer","fermergroupe"],classe:"groupe",react:"\u{1F512}",desc:e("close.desc")},async(n,c,{repondre:s,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o})=>{if(!i)return s(e("misc.group"));if(!o)return s(e("misc.admin"));if(!a)return s(e("misc.botAdmin"));try{await c.groupSettingUpdate(n,"announcement"),s(e("close.success"))}catch{s(e("misc.error"))}}),p({name:e("listmembers.name"),alias:["membres","listmembre"],classe:"groupe",react:"\u{1F465}",desc:e("listmembers.desc")},async(n,c,{repondre:s,verif_Gp:i,mbre_membre:a,nom_Gp:o,resolveName:r})=>{if(!i)return s(e("misc.group"));let u="",m="",l=0,y=0;a.forEach(g=>{const f=r(g.id);g.admin?(l++,u+=t.LINE(`${l}. ${f}
`)):(y++,m+=t.LINE(`${y}. ${f}
`))});let d=t.TOP(e("listmembers.title",{group:o.toUpperCase()}))+`
`;d+=t.LINE(`${e("listmembers.total",{count:a.length})}
`),l>0&&(d+=t.INTER()+`
`,d+=t.LINE(`${e("listmembers.admins",{count:l})}
`)+u),y>0&&(d+=t.INTER()+`
`,d+=t.LINE(`${e("listmembers.members",{count:y})}
`)+m),d+=t.BTM;const w=a.map(g=>g.id);await c.sendMessage(n,{text:d+N,mentions:w})}),p({name:e("setdesc.name"),alias:["desc","description"],classe:"groupe",react:"\u{1F4DD}",desc:e("setdesc.desc")},async(n,c,{repondre:s,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o,arg:r,prefixe:u})=>{if(!i)return s(e("misc.group"));if(!o)return s(e("misc.admin"));if(!a)return s(e("misc.botAdmin"));const m=r.join(" ");if(!m)return s(t.TOP("\u274C ERREUR")+`
`+t.LINE(`${e("setdesc.usage",{prefixe:u})}
`)+t.BTM);try{await c.groupUpdateDescription(n,m),s(e("setdesc.success"))}catch{s(e("misc.error"))}}),p({name:e("setname.name"),alias:["renommer","nomgroupe"],classe:"groupe",react:"\u270F\uFE0F",desc:e("setname.desc")},async(n,c,{repondre:s,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o,arg:r,prefixe:u})=>{if(!i)return s(e("misc.group"));if(!o)return s(e("misc.admin"));if(!a)return s(e("misc.botAdmin"));const m=r.join(" ");if(!m)return s(t.TOP("\u274C ERREUR")+`
`+t.LINE(`${e("setname.usage",{prefixe:u})}
`)+t.BTM);try{await c.groupUpdateSubject(n,m),s(e("setname.success",{name:m}))}catch{s(e("misc.error"))}}),p({name:e("linkgroupe.name"),alias:["link","invitelink"],classe:"groupe",react:"\u{1F517}",desc:e("linkgroupe.desc")},async(n,c,{repondre:s,verif_Gp:i,verif_menmaAdmin:a,verif_Admin:o})=>{if(!i)return s(e("misc.group"));if(!o)return s(e("misc.admin"));if(!a)return s(e("misc.botAdmin"));try{const r=await c.groupInviteCode(n);s(e("linkgroupe.msg",{code:r}))}catch{s(e("misc.error"))}}),p({name:e("infogroupe.name"),alias:["groupinfo","infogp"],classe:"groupe",react:"\u2139\uFE0F",desc:e("infogroupe.desc")},async(n,c,{repondre:s,verif_Gp:i,infos_Gp:a,mbre_membre:o,admins:r})=>{if(!i)return s(e("misc.group"));const u=a.creation?new Date(a.creation*1e3).toLocaleDateString("fr-FR"):"Inconnue",m=`${t.TOP(e("infogroupe.title"))}
${t.LINE(e("infogroupe.label_name",{name:a.subject||"N/A"}))}
${t.LINE(e("infogroupe.label_members",{count:o.length}))}
${t.LINE(e("infogroupe.label_admins",{count:r.length}))}
${t.LINE(e("infogroupe.label_date",{date:u}))}
${t.BTM}
${t.TOP(e("infogroupe.label_desc"))}
${a.desc||e("infogroupe.no_desc")}`;s(m+N)}),p({name:e("clear.name"),alias:["clean","vider"],classe:"groupe",react:"\u{1F9F9}",desc:e("clear.desc")},async(n,c,{repondre:s,verif_Admin:i,is_Owner:a,verif_Gp:o,ms:r})=>{if(o&&!i&&!a)return s(e("clear.no_admin"));if(!o&&!a)return s(e("misc.owner"));try{const u={key:r.key,messageTimestamp:r.messageTimestamp};try{await c.chatModify({clear:{messages:[u]}},n)}catch{await c.chatModify({clear:!0,lastMessages:[u]},n)}s(t.TOP("NETTOYAGE")+`
`+t.LINE(`${e("clear.success")}
`)+t.BTM)}catch(u){console.error("[CLEAR ERROR]",u),s(t.TOP("\u274C ERREUR")+`
`+t.LINE(`${e("clear.error")}
`)+t.BTM)}});import"../Database/settings.js";p({name:"setfooter",alias:["footer"],classe:"outils",react:"\u{1F58B}\uFE0F",desc:"Configure le footer personnalis\xE9 du bot (appara\xEEt sur les commandes)."},async(n,c,{repondre:s,is_Owner:i,arg:a})=>{if(!i)return s("\u274C Cette commande est r\xE9serv\xE9e au propri\xE9taire.");const o=a.join(" ");if(!o)return s(`\u274C Veuillez entrer le texte de votre footer apr\xE8s la commande.

*Exemple* : .setfooter Cr\xE9\xE9 par Dr Djibi`);try{const{updateSetting:r}=await import("../Database/settings.js");await r("customFooter",o),s(`\u2705 *Footer personnalis\xE9 enregistr\xE9 !*

Il s'affichera d\xE9sormais sur le menu et les autres commandes officielles.`)}catch{s(e("misc.error"))}}),p({name:"getfooter",alias:["viewfoot","showfooter"],classe:"outils",react:"\u{1F440}",desc:"Voir le footer personnalis\xE9 actuel."},async(n,c,{repondre:s,is_Owner:i})=>{if(!i)return s(e("misc.owner"));try{const{getSettings:a}=await import("../Database/settings.js"),o=await a();if(!o.customFooter)return s("\u2139\uFE0F Aucun footer personnalis\xE9 n'est configur\xE9.");s(`\u{1F4DD} *Votre footer actuel :*

${o.customFooter}`)}catch{s(e("misc.error"))}}),p({name:"delfooter",alias:["delfoot","removefooter"],classe:"outils",react:"\u{1F9F9}",desc:"Supprimer le footer personnalis\xE9."},async(n,c,{repondre:s,is_Owner:i})=>{if(!i)return s(e("misc.owner"));try{const{updateSetting:a}=await import("../Database/settings.js");await a("customFooter",""),s("\u2705 *Footer personnalis\xE9 supprim\xE9 avec succ\xE8s !*")}catch{s(e("misc.error"))}});
