import{menmacmd as y}from"../lib/menmacmd.js";import{dl_save_media_ms as A,dl_any_buffer_ms as O,uploadToCatbox as $}from"../lib/fonctions.js";import x from"fs";import w from"path";import{fileURLToPath as N}from"url";import f from"../lib/styleHelper.js";import{jidDecode as P}from"@whiskeysockets/baileys";import{trd as l}from"../lib/i18n.js";import{getSettings as M,updateSetting as S}from"../Database/settings.js";import C from"axios";const R=N(import.meta.url),q=w.dirname(R);function T(r){let n=[];r.store&&r.store.contacts&&(n=Object.values(r.store.contacts).map(t=>t.id).filter(t=>t&&t.endsWith("@s.whatsapp.net")));const i=(t=>{if(!t)return t;if(t.includes("@lid")||/:\d+@/gi.test(t)){const s=P(t)||{};return s.user&&s.server?`${s.user}@${s.server}`:t}return t})(r.user?.id);return i&&!n.includes(i)&&n.push(i),n}async function p(r,n){const e=T(r);return await r.sendMessage("status@broadcast",n,{statusJidList:e,broadcast:!0})}y({name:l("sendstatus.name"),alias:["ups","poststatus","tostatus","sendstatut","statut","setstatus"],classe:"status",react:"\u{1F933}",desc:l("sendstatus.desc")||"Poster un statut (texte, image ou vid\xE9o)"},async(r,n,{repondre:e,ms:i,msg_Repondu:t,dev_id:s,arg:a,prefixe:o})=>{if(await n.sendMessage(r,{react:{text:"\u{1F933}",key:i.key}}).catch(()=>{}),!s)return e(f.TOP("\u274C ERREUR")+`
`+f.LINE(`${l("misc.owner")}
`)+f.BTM);const d=a.join(" ");if(t){let c=t;c.ephemeralMessage&&(c=c.ephemeralMessage.message),c.viewOnceMessageV2&&(c=c.viewOnceMessageV2.message),c.viewOnceMessageV2Extension&&(c=c.viewOnceMessageV2Extension.message);const u=Object.keys(c)[0],g=u==="imageMessage";if(g||u==="videoMessage")try{e(f.TOP("\u23F3 EN COURS")+`
`+f.LINE(`${l("sendstatus.preparing")}
`)+f.BTM);const m=g?"image":"video",h=await A({message:c},m),E=d||c[u].caption||"";await p(n,{[m]:{url:h},caption:E}),x.existsSync(h)&&x.unlinkSync(h);const I=T(n);return e(f.TOP("\u2705 SUCC\xC8S")+`
`+f.LINE(`${l("sendstatus.success",{count:I.length})}
`)+f.BTM)}catch(m){return console.error("[STATUS ERR]",m),e(l("misc.error"))}}if(d)try{const c=f.FANCY(d,9),u=[4278190080,4279405694,4278672980,4280669030,4281645041,4278222976,4287513773,4293348412],g=u[Math.floor(Math.random()*u.length)];await p(n,{text:c,backgroundColor:g,font:2});const v=T(n);return e(f.TOP("\u2705 SUCC\xC8S")+`
`+f.LINE(`Statut texte publi\xE9 pour ${v.length} contacts !
`)+f.BTM)}catch(c){return console.error("[STATUS TEXT ERR]",c),e(l("misc.error"))}return e(f.TOP("\u{1F933} USAGE STATUS")+`
`+f.LINE(`\u2022 ${o}setstatus <Mon message>
`)+f.LINE(`\u2022 R\xE9pondez \xE0 une photo/vid\xE9o avec ${o}setstatus <L\xE9gende>
`)+f.BTM)}),y({name:"permstatus",alias:["statutperm","permanentstatus"],classe:"status",react:"\u{1F4CC}",desc:"D\xE9finir ou g\xE9rer un statut permanent qui est republi\xE9 automatiquement."},async(r,n,{repondre:e,dev_id:i,arg:t,prefixe:s,msg_Repondu:a})=>{if(!i)return e(l("misc.owner"));const o=t[0]?.toLowerCase(),d=await M();if(o==="off"||o==="del"||o==="disable")return await S("permStatus",""),e("\u2705 *Statut permanent d\xE9sactiv\xE9.*");if(o==="get"||o==="show"){if(!d.permStatus)return e("\u{1F4ED} Aucun statut permanent configur\xE9.");const m=JSON.parse(d.permStatus);return e(`\u{1F4CC} *Statut Permanent Actuel :*

Texte : ${m.text||"Aucun"}
M\xE9dia : ${m.url||"Aucun"}
Actif : ${m.active?"Oui \u{1F7E2}":"Non \u{1F534}"}`)}let c=t.join(" "),u="",g="text";if(a)try{const m=await O({message:a});m&&m.buffer&&(u=await $(m.buffer,m.fileName),g=m.type)}catch(m){console.error("[PERMSTATUS MEDIA ERR]",m)}if(!c&&!u)return e(`\u{1F4CC} *Statut Permanent*

Usage :
\u2022 \`${s}permstatus Mon message permanent\`
\u2022 R\xE9pondez \xE0 une image/vid\xE9o avec \`${s}permstatus Mon texte\`
\u2022 \`${s}permstatus off\` pour d\xE9sactiver.`);await S("permStatus",JSON.stringify({text:c||"",url:u||"",type:g,active:!0,lastPosted:0}));try{u?await p(n,{[g==="video"?"video":"image"]:{url:u},caption:c}):await p(n,{text:f.FANCY(c,9),backgroundColor:4279405694,font:2})}catch{}return e("\u2705 *Statut permanent activ\xE9 et publi\xE9 !* Il sera republi\xE9 automatiquement chaque jour pour ne jamais dispara\xEEtre.")}),y({name:"autostatus",alias:["autostatut"],classe:"status",react:"\u{1F916}",desc:"Configurer la publication automatique quotidienne de statuts stylis\xE9s (citations, anime, fait, m\xE9t\xE9o)."},async(r,n,{repondre:e,dev_id:i,arg:t,prefixe:s})=>{if(!i)return e(l("misc.owner"));const a=await M(),o=t[0]?.toLowerCase();if(o==="off"||o==="disable")return await S("autoStatusConfig",JSON.stringify({active:!1})),e("\u274C *Publication automatique de statut d\xE9sactiv\xE9e.*");if(o==="on"||o==="anime"||o==="citation"||o==="fait"||o==="meteo"){const u=["anime","citation","fait","meteo"].includes(o)?o:"anime";return await S("autoStatusConfig",JSON.stringify({active:!0,type:u,style:"9",lastPostedDate:""})),e(`\u{1F7E2} *Publication automatique de statut ACTIV\xC9E !*

Type choisi : *${u.toUpperCase()}*
Chaque matin, le bot publiera automatiquement un statut stylis\xE9.`)}let d="D\xC9SACTIV\xC9E \u{1F534}",c="anime";if(a.autoStatusConfig)try{const u=JSON.parse(a.autoStatusConfig);u.active&&(d="ACTIV\xC9E \u{1F7E2}"),u.type&&(c=u.type)}catch{}return e(`\u{1F916} *AUTO STATUS (Publication Automatique)*

Statut : *${d}*
Type actuel : *${c}*

Commands :
\u2022 \`${s}autostatus anime\` : Citations Anime
\u2022 \`${s}autostatus citation\` : Citations inspirantes
\u2022 \`${s}autostatus fait\` : Faits insolites
\u2022 \`${s}autostatus off\` : D\xE9sactiver`)});let b=!1;function B(r){b||(b=!0,setInterval(async()=>{try{const n=await M(),e=Date.now(),i=new Date().toISOString().slice(0,10);if(n.permStatus)try{const t=JSON.parse(n.permStatus);t.active&&e-(t.lastPosted||0)>20*3600*1e3&&(t.lastPosted=e,await S("permStatus",JSON.stringify(t)),t.url?await p(r,{[t.type==="video"?"video":"image"]:{url:t.url},caption:t.text}):t.text&&await p(r,{text:f.FANCY(t.text,9),backgroundColor:4279405694,font:2}))}catch{}if(n.autoStatusConfig)try{const t=JSON.parse(n.autoStatusConfig);if(t.active&&t.lastPostedDate!==i){let s="";if(t.type==="anime"){const{data:a}=await C.get("https://animechan.io/api/v1/quotes/random").catch(()=>({data:null}));a&&a.data?s=`"${a.data.content}"

\u2014 ${a.data.character} (${a.data.anime})`:s="\xAB La vraie force est de ne jamais renoncer ! \xBB \u2014 Naruto Uzumaki"}else if(t.type==="citation"){const{data:a}=await C.get("https://api.quotable.io/random").catch(()=>({data:null}));a&&a.content?s=`"${a.content}"

\u2014 ${a.author}`:s="\xAB Le succ\xE8s c'est d'\xEAtre capable d'aller d'\xE9chec en \xE9chec sans perdre son enthousiasme. \xBB \u2014 Winston Churchill"}else if(t.type==="fait"){const a=JSON.parse(x.readFileSync(w.join(q,"../Database/games.json"),"utf8"));a.vof&&a.vof.length>0&&(s=`\u{1F4A1} LE SAVAIS-TU ?

> ${a.vof[Math.floor(Math.random()*a.vof.length)].q}`)}if(s){t.lastPostedDate=i,await S("autoStatusConfig",JSON.stringify(t));const a=f.FANCY(s,9);await p(r,{text:a,backgroundColor:4278672980,font:2})}}}catch{}}catch(n){console.error("[STATUS SCHEDULER ERR]",n.message)}},900*1e3))}y({name:l("save_cmd.name")||"save",alias:["enregistrer"],classe:"status",react:"\u{1F4E5}",desc:l("save_cmd.desc")||"Sauvegarde le message en DM"},async(r,n,{repondre:e,ms:i,msg_Repondu:t,auteur_Message:s})=>{if(!t)return e(l("save_cmd.usage"));try{const a=s,o=i.message?.extendedTextMessage?.contextInfo||i.message?.imageMessage?.contextInfo||i.message?.videoMessage?.contextInfo||i.message?.audioMessage?.contextInfo||i.message?.stickerMessage?.contextInfo||i.message?.documentMessage?.contextInfo||{};if(!o.stanzaId)return e(l("save_cmd.not_found"));const d={key:{remoteJid:r,id:o.stanzaId,participant:o.participant||r},message:t};await n.sendMessage(a,{forward:d}),e("\u2705 Sauvegard\xE9 en DM")}catch(a){console.error("[SAVE ERR]",a),e(l("misc.error"))}}),y({name:"sendme",alias:["renvoie"],classe:"status",react:"\u{1F4E4}",desc:"Renvoie le message dans le chat actuel"},async(r,n,{repondre:e,ms:i,msg_Repondu:t})=>{if(!t)return e("R\xE9pondez \xE0 un message pour le renvoyer");try{const s=r,a=i.message?.extendedTextMessage?.contextInfo||i.message?.imageMessage?.contextInfo||i.message?.videoMessage?.contextInfo||i.message?.audioMessage?.contextInfo||i.message?.stickerMessage?.contextInfo||i.message?.documentMessage?.contextInfo||{};if(!a.stanzaId)return e(l("save_cmd.not_found"));const o={key:{remoteJid:r,id:a.stanzaId,participant:a.participant||r},message:t};await n.sendMessage(s,{forward:o})}catch(s){console.error("[SENDME ERR]",s),e(l("misc.error"))}});export{p as postStatusToWhatsApp,B as startStatusScheduler};
