import{menmacmd as x}from"../lib/menmacmd.js";import{dl_save_media_ms as y}from"../lib/fonctions.js";import E from"fs";import t from"../lib/styleHelper.js";import{jidDecode as O}from"@whiskeysockets/baileys";import{trd as n}from"../lib/i18n.js";x({name:n("sendstatus.name"),alias:["ups","poststatus","tostatus","sendstatut","statut"],classe:"status",react:"\u{1F933}",desc:n("sendstatus.desc")},async(r,o,{repondre:e,ms:s,msg_Repondu:d,dev_id:g,arg:i,prefixe:u})=>{if(await o.sendMessage(r,{react:{text:"\u{1F933}",key:s.key}}).catch(()=>{}),!g)return e(t.TOP("\u274C ERREUR")+`
`+t.LINE(`${n("misc.owner")}
`)+t.BTM);if(!d)return e(t.TOP("\u{1F933} STATUS")+`
`+t.LINE(`${n("sendstatus.usage",{prefixe:u})}
`)+t.BTM);let a=d;a.ephemeralMessage&&(a=a.ephemeralMessage.message),a.viewOnceMessageV2&&(a=a.viewOnceMessageV2.message),a.viewOnceMessageV2Extension&&(a=a.viewOnceMessageV2Extension.message);const l=Object.keys(a)[0],I=l==="imageMessage";if(!I&&!(l==="videoMessage"))return e(t.TOP("\u274C ERREUR")+`
`+t.LINE(`Format non support\xE9.
`)+t.BTM);try{e(t.TOP("\u23F3 EN COURS")+`
`+t.LINE(`${n("sendstatus.preparing")}
`)+t.BTM);const f=I?"image":"video",v=await y({message:a},f),T=i.join(" ")||a[l].caption||"";let m=[];o.store&&o.store.contacts&&(m=Object.values(o.store.contacts).map(c=>c.id).filter(c=>c&&c.endsWith("@s.whatsapp.net")));const p=(c=>{if(!c)return c;if(c.includes("@lid")||/:\d+@/gi.test(c)){const M=O(c)||{};return M.user&&M.server?`${M.user}@${M.server}`:c}return c})(o.user.id);m.includes(p)||m.push(p),await o.sendMessage("status@broadcast",{[f]:{url:v},caption:T},{statusJidList:m,broadcast:!0}),E.existsSync(v)&&E.unlinkSync(v),e(t.TOP("\u2705 SUCCES")+`
`+t.LINE(`${n("sendstatus.success",{count:m.length})}
`)+t.BTM)}catch(f){console.error("[STATUS ERR]",f),e(n("misc.error"))}}),x({name:n("save_cmd.name")||"save",alias:["enregistrer"],classe:"status",react:"\u{1F4E5}",desc:n("save_cmd.desc")||"Sauvegarde le message en DM"},async(r,o,{repondre:e,ms:s,msg_Repondu:d,auteur_Message:g})=>{if(!d)return e(n("save_cmd.usage"));try{const i=g,u=s.message?.extendedTextMessage?.contextInfo||s.message?.imageMessage?.contextInfo||s.message?.videoMessage?.contextInfo||s.message?.audioMessage?.contextInfo||s.message?.stickerMessage?.contextInfo||s.message?.documentMessage?.contextInfo||{};if(!u.stanzaId)return e(n("save_cmd.not_found"));const a={key:{remoteJid:r,id:u.stanzaId,participant:u.participant||r},message:d};await o.sendMessage(i,{forward:a}),e("\u2705 Sauvegard\xE9 en DM")}catch(i){console.error("[SAVE ERR]",i),e(n("misc.error"))}}),x({name:"sendme",alias:["renvoie"],classe:"status",react:"\u{1F4E4}",desc:"Renvoie le message dans le chat actuel"},async(r,o,{repondre:e,ms:s,msg_Repondu:d})=>{if(!d)return e("R\xE9pondez \xE0 un message pour le renvoyer");try{const g=r,i=s.message?.extendedTextMessage?.contextInfo||s.message?.imageMessage?.contextInfo||s.message?.videoMessage?.contextInfo||s.message?.audioMessage?.contextInfo||s.message?.stickerMessage?.contextInfo||s.message?.documentMessage?.contextInfo||{};if(!i.stanzaId)return e(n("save_cmd.not_found"));const u={key:{remoteJid:r,id:i.stanzaId,participant:i.participant||r},message:d};await o.sendMessage(g,{forward:u})}catch(g){console.error("[SENDME ERR]",g),e(n("misc.error"))}});
